<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;


class CitySeederDev extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {


        $cities= [
            ['province_id'=>2, 'name'=>'CABA'],
            ['province_id'=>2, 'name'=>'CONSTITUCION'],
            ['province_id'=>2, 'name'=>'MONSERRAT'],
            ['province_id'=>2, 'name'=>'PUERTO MADERO'],
            ['province_id'=>2, 'name'=>'RETIRO'],
            ['province_id'=>2, 'name'=>'SAN NICOLAS'],
            ['province_id'=>2, 'name'=>'SAN TELMO'],
            ['province_id'=>2, 'name'=>'RECOLETA'],
            ['province_id'=>2, 'name'=>'BALVANERA'],
            ['province_id'=>2, 'name'=>'SAN CRISTOBAL'],
            ['province_id'=>2, 'name'=>'BARRACAS'],
            ['province_id'=>2, 'name'=>'BOCA'],
            ['province_id'=>2, 'name'=>'NUEVA POMPEYA'],
            ['province_id'=>2, 'name'=>'PARQUE PATRICIOS'],
            ['province_id'=>2, 'name'=>'ALMAGRO'],
            ['province_id'=>2, 'name'=>'BOEDO'],
            ['province_id'=>2, 'name'=>'CABALLITO'],
            ['province_id'=>2, 'name'=>'FLORES'],
            ['province_id'=>2, 'name'=>'PARQUE CHACABUCO'],
            ['province_id'=>2, 'name'=>'VILLA LUGANO'],
            ['province_id'=>2, 'name'=>'BELGRANO'],
            ['province_id'=>2, 'name'=>'COLEGIALES'],
            ['province_id'=>2, 'name'=>'NUÑEZ'],
            ['province_id'=>2, 'name'=>'PALERMO'],
            ['province_id'=>2, 'name'=>'AGRONOMIA'],
            ['province_id'=>2, 'name'=>'CHACARITA'],
            ['province_id'=>2, 'name'=>'PARQUE CHAS'],
            ['province_id'=>2, 'name'=>'PATERNAL'],
            ['province_id'=>2, 'name'=>'VILLA CRESPO'],
            ['province_id'=>2, 'name'=>'VILLA ORTUZAR'],
            ['province_id'=>6, 'name'=>'LOS 4 CAMINOS'],
            ['province_id'=>6, 'name'=>'LOS ANGELES'],
            ['province_id'=>6, 'name'=>'CORONEL ROSALES'],
            ['province_id'=>6, 'name'=>'LAS OSCURAS'],
            ['province_id'=>6, 'name'=>'PATRICIOS'],
            ['province_id'=>6, 'name'=>'BAJO HONDO'],
            ['province_id'=>6, 'name'=>'BALNEARIO PEHUEN CO'],
            ['province_id'=>6, 'name'=>'PAGO CHICO'],
            ['province_id'=>6, 'name'=>'PUNTA ALTA'],
            ['province_id'=>6, 'name'=>'PUNTA ALTA'],
            ['province_id'=>6, 'name'=>'VILLA DEL MAR'],
            ['province_id'=>6, 'name'=>'VILLA GENERAL ARIAS'],
            ['province_id'=>6, 'name'=>'CALVO'],
            ['province_id'=>6, 'name'=>'CENTRO URQUIZA'],
            ['province_id'=>6, 'name'=>'CUARTEL II'],
            ['province_id'=>6, 'name'=>'EL CALFIAO'],
            ['province_id'=>6, 'name'=>'EL LUCERO'],
            ['province_id'=>6, 'name'=>'EL ZORRO'],
            ['province_id'=>6, 'name'=>'GIL'],
            ['province_id'=>6, 'name'=>'LA AURORA'],
            ['province_id'=>6, 'name'=>'PEDRO LURO'],
            ['province_id'=>6, 'name'=>'TENIENTE ORIGONE'],
            ['province_id'=>6, 'name'=>'ATUCHA'],
            ['province_id'=>6, 'name'=>'CUARTEL V'],
            ['province_id'=>6, 'name'=>'EL TATU'],
            ['province_id'=>6, 'name'=>'ISLA BOTIJA'],
            ['province_id'=>6, 'name'=>'ISLAS'],
            ['province_id'=>6, 'name'=>'LA PESQUERIA'],
            ['province_id'=>6, 'name'=>'LAS CUATRO ESQUINAS'],
            ['province_id'=>6, 'name'=>'LAS PALMAS'],
            ['province_id'=>6, 'name'=>'RUTA 9 KM 103'],
            ['province_id'=>6, 'name'=>'COUNTRY CLUB EL CASCO'],
            ['province_id'=>6, 'name'=>'ESCALADA'],
            ['province_id'=>6, 'name'=>'LIMA'],
            ['province_id'=>6, 'name'=>'ZARATE'],
            ['province_id'=>6, 'name'=>'BARRIO SAAVEDRA'],
            ['province_id'=>6, 'name'=>'ZARATE'],
            ['province_id'=>10, 'name'=>'HUMAYA'],
            ['province_id'=>10, 'name'=>'ISLA LARGA'],
            ['province_id'=>10, 'name'=>'LA PUERTA SUD'],
            ['province_id'=>10, 'name'=>'LA SALVIA'],
            ['province_id'=>10, 'name'=>'RIO DE LAS CASAS VIEJAS'],
            ['province_id'=>10, 'name'=>'CHUCHUCARUANA'],
            ['province_id'=>10, 'name'=>'COLPES'],
            ['province_id'=>10, 'name'=>'CORDOBITA'],
            ['province_id'=>10, 'name'=>'COSTA DE REYES'],
            ['province_id'=>10, 'name'=>'EL PUEBLITO'],
            ['province_id'=>10, 'name'=>'EL PUESTO'],
            ['province_id'=>10, 'name'=>'EL SALADO'],
            ['province_id'=>10, 'name'=>'FIAMBALA'],
            ['province_id'=>10, 'name'=>'LA RAMADITA'],
            ['province_id'=>10, 'name'=>'PAMPA BLANCA'],
            ['province_id'=>10, 'name'=>'LOS BALVERDIS'],
            ['province_id'=>10, 'name'=>'MEDANITOS'],
            ['province_id'=>10, 'name'=>'PALO BLANCO'],
            ['province_id'=>10, 'name'=>'PUNTA DEL AGUA'],
            ['province_id'=>10, 'name'=>'SAUJIL'],
            ['province_id'=>10, 'name'=>'TATON'],
            ['province_id'=>10, 'name'=>'TINOGASTA'],
            ['province_id'=>10, 'name'=>'AGUA COLORADA'],
            ['province_id'=>10, 'name'=>'ANTAPOCA'],
            ['province_id'=>10, 'name'=>'LAS ESQUINAS'],
            ['province_id'=>10, 'name'=>'LOS ARBOLITOS'],
            ['province_id'=>10, 'name'=>'EL PORTEZUELO'],
            ['province_id'=>10, 'name'=>'HUAYCAMA'],
            ['province_id'=>10, 'name'=>'LAS TEJAS'],
            ['province_id'=>10, 'name'=>'EL BAÑADO'],
            ['province_id'=>10, 'name'=>'POLCOS'],
            ['province_id'=>10, 'name'=>'POZO DEL MISTOL'],
            ['province_id'=>10, 'name'=>'SAN ISIDRO'],
            ['province_id'=>10, 'name'=>'SANTA ROSA'],
            ['province_id'=>10, 'name'=>'SUMALAO'],
            ['province_id'=>10, 'name'=>'VILLA DOLORES'],
            ['province_id'=>10, 'name'=>'SANTA CRUZ'],
            ['province_id'=>14, 'name'=>'ARROYO SECO'],
            ['province_id'=>14, 'name'=>'ATOS PAMPA'],
            ['province_id'=>14, 'name'=>'CAPILLA DEL CARMEN'],
            ['province_id'=>14, 'name'=>'NOETINGER'],
            ['province_id'=>14, 'name'=>'ORDOÑEZ'],
            ['province_id'=>14, 'name'=>'PASCANAS'],
            ['province_id'=>14, 'name'=>'PUEBLO ITALIANO'],
            ['province_id'=>14, 'name'=>'RAMON J. CARCANO'],
            ['province_id'=>14, 'name'=>'SAN ANTONIO DE LITIN'],
            ['province_id'=>14, 'name'=>'SAN MARCOS'],
            ['province_id'=>14, 'name'=>'SAN SEVERO'],
            ['province_id'=>14, 'name'=>'VIAMONTE'],
            ['province_id'=>14, 'name'=>'VILLA LOS PATOS'],
            ['province_id'=>14, 'name'=>'WENCESLAO ESCALANTE'],
            ['province_id'=>14, 'name'=>'Sierras de Cordoba'],
            ['province_id'=>18, 'name'=>'CARRIZAL NORTE'],
            ['province_id'=>18, 'name'=>'CEBOLLAS'],
            ['province_id'=>18, 'name'=>'COLONIA 3 DE ABRIL'],
            ['province_id'=>18, 'name'=>'COLONIA PROGRESO'],
            ['province_id'=>18, 'name'=>'DESMOCHADO'],
            ['province_id'=>18, 'name'=>'ISLA ALTA'],
            ['province_id'=>18, 'name'=>'JUAN DIAZ'],
            ['province_id'=>18, 'name'=>'LAS GARZAS'],
            ['province_id'=>18, 'name'=>'LOMAS ESTE'],
            ['province_id'=>18, 'name'=>'LOMAS NORTE'],
            ['province_id'=>18, 'name'=>'LA ESTRELLA'],
            ['province_id'=>18, 'name'=>'LOMA ALTA'],
            ['province_id'=>18, 'name'=>'LOS EUCALIPTOS'],
            ['province_id'=>18, 'name'=>'MALEZAL'],
            ['province_id'=>18, 'name'=>'OVEJITA'],
            ['province_id'=>18, 'name'=>'PASO BERMUDEZ'],
            ['province_id'=>18, 'name'=>'RINCON DE ANIMAS'],
            ['province_id'=>18, 'name'=>'RINCON DEL SAUCE'],
            ['province_id'=>18, 'name'=>'SAN MARTIN'],
            ['province_id'=>18, 'name'=>'SAN PEDRO'],
            ['province_id'=>18, 'name'=>'SAN RAMON'],
            ['province_id'=>18, 'name'=>'SAUCE'],
            ['province_id'=>22, 'name'=>'9 DE JULIO'],
            ['province_id'=>22, 'name'=>'ALTA ESPERANZA'],
            ['province_id'=>22, 'name'=>'CASTELLI'],
            ['province_id'=>22, 'name'=>'CHACO PORA'],
            ['province_id'=>22, 'name'=>'COLONIA PAMPA BOLSA SUR'],
            ['province_id'=>22, 'name'=>'COLONIA PAMPA UNION'],
            ['province_id'=>22, 'name'=>'CUATRO BOCAS'],
            ['province_id'=>22, 'name'=>'EL ARENAL'],
            ['province_id'=>22, 'name'=>'EL BRASIL'],
            ['province_id'=>22, 'name'=>'EL INDIO'],
            ['province_id'=>22, 'name'=>'EL LEBRETON'],
            ['province_id'=>22, 'name'=>'EL PARAISO'],
            ['province_id'=>22, 'name'=>'EL PINTADO'],
            ['province_id'=>22, 'name'=>'EL QUINTO'],
            ['province_id'=>22, 'name'=>'PASO DEL OSO'],
            ['province_id'=>22, 'name'=>'PUEBLO VIEJO'],
            ['province_id'=>22, 'name'=>'SANTA MARTA'],
            ['province_id'=>22, 'name'=>'COLONIA ABORIGEN'],
            ['province_id'=>22, 'name'=>'MACHAGAI'],
            ['province_id'=>22, 'name'=>'NAPALPI'],
            ['province_id'=>26, 'name'=>'BAJO DEL GUALICHO'],
            ['province_id'=>26, 'name'=>'EL RIACHO SAN JOSE'],
            ['province_id'=>26, 'name'=>'PUNTA DELGADA'],
            ['province_id'=>26, 'name'=>'PUNTA NORTE'],
            ['province_id'=>26, 'name'=>'ARROYO VERDE'],
            ['province_id'=>26, 'name'=>'PUERTO MADRYN'],
            ['province_id'=>26, 'name'=>'PUERTO PIRAMIDE'],
            ['province_id'=>26, 'name'=>'QUINTA EL MIRADOR'],
            ['province_id'=>26, 'name'=>'RESERVA AREA PROTEGIDA EL DORADILLO'],
            ['province_id'=>26, 'name'=>'CERRO RADAL'],
            ['province_id'=>26, 'name'=>'EL BLANCO'],
            ['province_id'=>26, 'name'=>'EL CAJON'],
            ['province_id'=>26, 'name'=>'EL COIHUE'],
            ['province_id'=>26, 'name'=>'EL MAYOCO'],
            ['province_id'=>26, 'name'=>'EL MIRADOR'],
            ['province_id'=>26, 'name'=>'EL PORTEZUELO'],
            ['province_id'=>26, 'name'=>'EL RINCON'],
            ['province_id'=>26, 'name'=>'EL TURBIO'],
            ['province_id'=>26, 'name'=>'ENTRE RIOS'],
            ['province_id'=>26, 'name'=>'LA ISLA'],
            ['province_id'=>26, 'name'=>'LAS GOLONDRINAS'],
            ['province_id'=>26, 'name'=>'RIO CHICO'],
            ['province_id'=>26, 'name'=>'VILLA LAGO RIVADAVIA'],
            ['province_id'=>26, 'name'=>'BUENOS AIRES CHICO'],
            ['province_id'=>26, 'name'=>'CHOLILA'],
            ['province_id'=>26, 'name'=>'COSTA DE CHUBUT'],
            ['province_id'=>26, 'name'=>'CUSHAMEN CENTRO'],
            ['province_id'=>26, 'name'=>'EL HOYO'],
            ['province_id'=>26, 'name'=>'EL MAITEN'],
            ['province_id'=>26, 'name'=>'EPUYEN'],
            ['province_id'=>26, 'name'=>'FOFO CAHUEL'],
            ['province_id'=>26, 'name'=>'GUALJAINA'],
            ['province_id'=>26, 'name'=>'LAGO EPUYEN'],
            ['province_id'=>26, 'name'=>'LAGO PUELO'],
            ['province_id'=>26, 'name'=>'LELEQUE'],
            ['province_id'=>26, 'name'=>'EL TORDILLO'],
            ['province_id'=>26, 'name'=>'EL TREBOL'],
            ['province_id'=>26, 'name'=>'HOLDICH'],
            ['province_id'=>26, 'name'=>'PAMPA DEL CASTILLO'],
            ['province_id'=>26, 'name'=>'CHASICO'],
            ['province_id'=>26, 'name'=>'MALLIN GRANDE'],
            ['province_id'=>26, 'name'=>'TALAGAPA'],
            ['province_id'=>26, 'name'=>'GAN GAN'],
            ['province_id'=>26, 'name'=>'TELSEN'],
            ['province_id'=>30, 'name'=>'ALDEA SAN GREGORIO'],
            ['province_id'=>30, 'name'=>'ARROYO CONCEPCION'],
            ['province_id'=>30, 'name'=>'COLONIA EL CARMEN'],
            ['province_id'=>30, 'name'=>'COLONIA IZQUIERDO'],
            ['province_id'=>30, 'name'=>'COLONIA LA MATILDE'],
            ['province_id'=>30, 'name'=>'COLONIA LAS MERCEDES'],
            ['province_id'=>30, 'name'=>'COLONIA LAS PEPAS'],
            ['province_id'=>30, 'name'=>'VILLA CLARA'],
            ['province_id'=>30, 'name'=>'VILLA DOMINGUEZ'],
            ['province_id'=>30, 'name'=>'VILLAGUAY'],
            ['province_id'=>34, 'name'=>'AHI VEREMOS'],
            ['province_id'=>34, 'name'=>'AIBAL EL SILENCIO'],
            ['province_id'=>34, 'name'=>'ALTO ALEGRE'],
            ['province_id'=>34, 'name'=>'BAJO HONDO'],
            ['province_id'=>34, 'name'=>'BAJO VERDE'],
            ['province_id'=>34, 'name'=>'CAMPO AZUL'],
            ['province_id'=>34, 'name'=>'TRES PALMAS'],
            ['province_id'=>34, 'name'=>'TRES POZOS'],
            ['province_id'=>34, 'name'=>'VILLA DEVOTO'],
            ['province_id'=>34, 'name'=>'EL POTRILLO'],
            ['province_id'=>34, 'name'=>'GENERAL MOSCONI'],
            ['province_id'=>34, 'name'=>'EL QUEBRACHO'],
            ['province_id'=>38, 'name'=>'AGUA CALIENTE DE LA PUNA'],
            ['province_id'=>38, 'name'=>'AGUA CHICA'],
            ['province_id'=>38, 'name'=>'EL MORENO'],
            ['province_id'=>38, 'name'=>'CERRO DE LOS 7 COLORES'],
            ['province_id'=>38, 'name'=>'PURMAMARCA'],
            ['province_id'=>38, 'name'=>'TUMBAYA'],
            ['province_id'=>38, 'name'=>'TAFNA'],
            ['province_id'=>38, 'name'=>'BARRIOS'],
            ['province_id'=>38, 'name'=>'CANGREJILLOS'],
            ['province_id'=>38, 'name'=>'EL CONDOR'],
            ['province_id'=>38, 'name'=>'LA INTERMEDIA'],
            ['province_id'=>38, 'name'=>'LA QUIACA'],
            ['province_id'=>38, 'name'=>'LLULLUCHAYOC'],
            ['province_id'=>38, 'name'=>'PUMAHUASI'],
            ['province_id'=>38, 'name'=>'SAN JOSE'],
            ['province_id'=>38, 'name'=>'YAVI CHICO'],
            ['province_id'=>42, 'name'=>'ATREUCO'],
            ['province_id'=>42, 'name'=>'CEREALES'],
            ['province_id'=>42, 'name'=>'COLONIA EL PROVENIR'],
            ['province_id'=>42, 'name'=>'ESTANCIA EL PAMPERO'],
            ['province_id'=>42, 'name'=>'HIDALGO'],
            ['province_id'=>42, 'name'=>'LA LOMA'],
            ['province_id'=>42, 'name'=>'DOBLAS'],
            ['province_id'=>42, 'name'=>'MACACHIN'],
            ['province_id'=>42, 'name'=>'MIGUEL RIGLOS'],
            ['province_id'=>42, 'name'=>'ROLON'],
            ['province_id'=>42, 'name'=>'TOMAS M. ANCHORENA'],
            ['province_id'=>42, 'name'=>'COLONIA LA COLORADA CHICA'],
            ['province_id'=>42, 'name'=>'COLONIA SAN ROSARIO'],
            ['province_id'=>42, 'name'=>'GAVIOTAS'],
            ['province_id'=>42, 'name'=>'ANZOATEGUI'],
            ['province_id'=>42, 'name'=>'LA ADELA'],
            ['province_id'=>42, 'name'=>'BARRANCAS COLORADAS'],
            ['province_id'=>42, 'name'=>'COLONIA INES Y CARLOTA'],
            ['province_id'=>42, 'name'=>'TRENEL'],
            ['province_id'=>42, 'name'=>'EL CARANCHO'],
            ['province_id'=>42, 'name'=>'EL VERANEO'],
            ['province_id'=>42, 'name'=>'EPU PEL'],
            ['province_id'=>42, 'name'=>'GAMAY'],
            ['province_id'=>42, 'name'=>'UTRACAN'],
            ['province_id'=>42, 'name'=>'VALLE DAZA'],
            ['province_id'=>42, 'name'=>'ATALIVA ROCA'],
            ['province_id'=>42, 'name'=>'CHACHARRAMENDI'],
            ['province_id'=>42, 'name'=>'COLONIA SANTA MARIA'],
            ['province_id'=>42, 'name'=>'GENERAL ACHA'],
            ['province_id'=>42, 'name'=>'QUEHUE'],
            ['province_id'=>42, 'name'=>'UNANUE'],
            ['province_id'=>46, 'name'=>'LA CANCHITA'],
            ['province_id'=>46, 'name'=>'LA CAUCHITA'],
            ['province_id'=>46, 'name'=>'LA CIMBRITA'],
            ['province_id'=>46, 'name'=>'TINOCAN'],
            ['province_id'=>46, 'name'=>'UDPINANGO'],
            ['province_id'=>46, 'name'=>'AIMOGASTA'],
            ['province_id'=>46, 'name'=>'MACHIGASTA'],
            ['province_id'=>46, 'name'=>'SAN ANTONIO'],
            ['province_id'=>46, 'name'=>'ARAUCO'],
            ['province_id'=>46, 'name'=>'BAÑADO DE LOS PANTANOS'],
            ['province_id'=>46, 'name'=>'ESTACION MAZAN'],
            ['province_id'=>46, 'name'=>'TERMAS DE SANTA TERESITA'],
            ['province_id'=>46, 'name'=>'VILLA MAZAN'],
            ['province_id'=>46, 'name'=>'AMPATA'],
            ['province_id'=>46, 'name'=>'EL VIRQUE'],
            ['province_id'=>46, 'name'=>'CHAUPIHUASI'],
            ['province_id'=>46, 'name'=>'CUIPAN'],
            ['province_id'=>46, 'name'=>'LAS TALAS'],
            ['province_id'=>46, 'name'=>'LOS ROBLES'],
            ['province_id'=>46, 'name'=>'SALICAS'],
            ['province_id'=>46, 'name'=>'SAN BLAS'],
            ['province_id'=>46, 'name'=>'SHAQUI'],
            ['province_id'=>46, 'name'=>'SURIYACO'],
            ['province_id'=>46, 'name'=>'TUYUBIL'],
            ['province_id'=>46, 'name'=>'HUACO'],
            ['province_id'=>46, 'name'=>'LA ESCALERA'],
            ['province_id'=>46, 'name'=>'LA TORRECITA'],
            ['province_id'=>46, 'name'=>'VILLA SANAGASTA'],
            ['province_id'=>50, 'name'=>'MENDOZA'],
            ['province_id'=>50, 'name'=>'2A. SECCION'],
            ['province_id'=>50, 'name'=>'3A. SECCION'],
            ['province_id'=>50, 'name'=>'4A. SECCION'],
            ['province_id'=>50, 'name'=>'5A. SECCION'],
            ['province_id'=>50, 'name'=>'6A. SECCION'],
            ['province_id'=>50, 'name'=>'7A. SECCION'],
            ['province_id'=>50, 'name'=>'8A. SECCION'],
            ['province_id'=>50, 'name'=>'ZAPATA'],
            ['province_id'=>50, 'name'=>'BARRIO BELGRANO NORTE'],
            ['province_id'=>50, 'name'=>'CORDON DEL PLATA'],
            ['province_id'=>50, 'name'=>'EL PERAL'],
            ['province_id'=>50, 'name'=>'EL ZAMPAL'],
            ['province_id'=>50, 'name'=>'LA ARBOLEDA'],
            ['province_id'=>50, 'name'=>'SAN JOSE'],
            ['province_id'=>50, 'name'=>'TUPUNGATO'],
            ['province_id'=>50, 'name'=>'VILLA BASTIAS'],
            ['province_id'=>54, 'name'=>'CAPON BONITO'],
            ['province_id'=>54, 'name'=>'COLONIA APOSTOLES'],
            ['province_id'=>54, 'name'=>'COLONIA SAN JOSE'],
            ['province_id'=>54, 'name'=>'EL CRUCE'],
            ['province_id'=>54, 'name'=>'VILLA AKERMAN'],
            ['province_id'=>54, 'name'=>'VILLA URRUTIA'],
            ['province_id'=>54, 'name'=>'AVELLANEDA'],
            ['province_id'=>54, 'name'=>'COLONIA GUARAYPO'],
            ['province_id'=>54, 'name'=>'COLONIA SANTA TERESA'],
            ['province_id'=>54, 'name'=>'GUATAMBU'],
            ['province_id'=>54, 'name'=>'EL BARRERITO'],
            ['province_id'=>54, 'name'=>'EL PALMITAL'],
            ['province_id'=>54, 'name'=>'EL SALTITO'],
            ['province_id'=>54, 'name'=>'FLOR DE MAYO'],
            ['province_id'=>54, 'name'=>'TAMANDUA'],
            ['province_id'=>54, 'name'=>'TORTA QUEMADA'],
            ['province_id'=>54, 'name'=>'ALBA POSSE'],
            ['province_id'=>54, 'name'=>'COLONIA ALICIA'],
            ['province_id'=>54, 'name'=>'ALICIA BAJA'],
            ['province_id'=>54, 'name'=>'COLONIA AURORA'],
            ['province_id'=>54, 'name'=>'SAN FRANCISCO DE ASIS'],
            ['province_id'=>54, 'name'=>'SANTA RITA'],
            ['province_id'=>54, 'name'=>'25 DE MAYO'],
            ['province_id'=>58, 'name'=>'ABRA ANCHA'],
            ['province_id'=>58, 'name'=>'CARRI LIL'],
            ['province_id'=>58, 'name'=>'LONCO LUAN'],
            ['province_id'=>58, 'name'=>'LOS HORNOS'],
            ['province_id'=>58, 'name'=>'MALLIN DEL MUERTO'],
            ['province_id'=>58, 'name'=>'PASO DE LOS INDIOS'],
            ['province_id'=>58, 'name'=>'PUENTE PICUN LEUFU'],
            ['province_id'=>58, 'name'=>'SANTO DOMINGO'],
            ['province_id'=>58, 'name'=>'LOS CATUTOS'],
            ['province_id'=>58, 'name'=>'COVUNCO CENTRO'],
            ['province_id'=>58, 'name'=>'MARIANO MORENO'],
            ['province_id'=>58, 'name'=>'RAMON M. CASTRO'],
            ['province_id'=>58, 'name'=>'ZAPALA'],
            ['province_id'=>62, 'name'=>'CUBANEA'],
            ['province_id'=>62, 'name'=>'EL PASO'],
            ['province_id'=>62, 'name'=>'LA BOCA'],
            ['province_id'=>62, 'name'=>'LA ENSENADA'],
            ['province_id'=>62, 'name'=>'MONTE BAGUAL'],
            ['province_id'=>62, 'name'=>'PRIMERA ANGOSTURA'],
            ['province_id'=>62, 'name'=>'SAUCE BLANCO'],
            ['province_id'=>62, 'name'=>'ZANJON DE OYUELA'],
            ['province_id'=>62, 'name'=>'BAHIA CREEK'],
            ['province_id'=>62, 'name'=>'EL CONDOR'],
            ['province_id'=>62, 'name'=>'INGENIERO JACOBACCI'],
            ['province_id'=>62, 'name'=>'LOS MENUCOS'],
            ['province_id'=>62, 'name'=>'MAQUINCHAO'],
            ['province_id'=>62, 'name'=>'MINA SANTA TERESITA'],
            ['province_id'=>62, 'name'=>'PILQUINIYEU'],
            ['province_id'=>66, 'name'=>'AGUA CALIENTE'],
            ['province_id'=>66, 'name'=>'AGUA SUCIA'],
            ['province_id'=>66, 'name'=>'ALGARROBAL'],
            ['province_id'=>66, 'name'=>'ALTO ALEGRE'],
            ['province_id'=>66, 'name'=>'ALTO BELLO'],
            ['province_id'=>66, 'name'=>'ANTA POZO'],
            ['province_id'=>66, 'name'=>'ARRAYANAL'],
            ['province_id'=>66, 'name'=>'BALBUENA'],
            ['province_id'=>66, 'name'=>'BELLA FLOR'],
            ['province_id'=>66, 'name'=>'BELLA VISTA'],
            ['province_id'=>66, 'name'=>'BOCA DEL TIGRE'],
            ['province_id'=>66, 'name'=>'UNQUILLO'],
            ['province_id'=>66, 'name'=>'ROSARIO DE LA FRONTERA'],
            ['province_id'=>66, 'name'=>'SAN FELIPE'],
            ['province_id'=>66, 'name'=>'AGUA CHICA'],
            ['province_id'=>70, 'name'=>'EL SALADO'],
            ['province_id'=>70, 'name'=>'TIERRA ADENTRO'],
            ['province_id'=>70, 'name'=>'EL RINCON'],
            ['province_id'=>70, 'name'=>'CAMPO AFUERA'],
            ['province_id'=>70, 'name'=>'LA CAÑADA'],
            ['province_id'=>70, 'name'=>'PACHACO'],
            ['province_id'=>70, 'name'=>'ZONDA ARRIBA'],
            ['province_id'=>70, 'name'=>'VILLA BASILIO NIEVAS'],
            ['province_id'=>70, 'name'=>'VILLA TACU'],
            ['province_id'=>74, 'name'=>'BALDE DE AZCURRA'],
            ['province_id'=>74, 'name'=>'BALDE DE LOS TORRES'],
            ['province_id'=>74, 'name'=>'BALDE DE QUINES'],
            ['province_id'=>74, 'name'=>'BALDE DEL CARMEN'],
            ['province_id'=>74, 'name'=>'BALDE RETAMO'],
            ['province_id'=>74, 'name'=>'BALDE ULTIMO'],
            ['province_id'=>74, 'name'=>'BALDE VIEJO'],
            ['province_id'=>74, 'name'=>'LA REPRESITA'],
            ['province_id'=>74, 'name'=>'LA SALVADORA'],
            ['province_id'=>74, 'name'=>'LA TRANCA'],
            ['province_id'=>74, 'name'=>'LAS CHACRAS'],
            ['province_id'=>74, 'name'=>'LAS CHIMBAS'],
            ['province_id'=>74, 'name'=>'LAS CLARITAS'],
            ['province_id'=>74, 'name'=>'LAS LAGUNITAS'],
            ['province_id'=>78, 'name'=>'EL CHALTEN'],
            ['province_id'=>78, 'name'=>'TRES LAGOS'],
            ['province_id'=>78, 'name'=>'EL PORTEZUELO'],
            ['province_id'=>78, 'name'=>'LA ARAGONESA'],
            ['province_id'=>78, 'name'=>'LA MANCHURIA'],
            ['province_id'=>78, 'name'=>'LOS ANTIGUOS'],
            ['province_id'=>78, 'name'=>'PERITO MORENO'],
            ['province_id'=>78, 'name'=>'BELLA VISTA'],
            ['province_id'=>78, 'name'=>'GLACIAR PERITO MORENO'],
            ['province_id'=>78, 'name'=>'FLORIDA NEGRA'],
            ['province_id'=>78, 'name'=>'PUERTO SAN JULIAN'],
            ['province_id'=>78, 'name'=>'LA PENINSULA'],
            ['province_id'=>78, 'name'=>'LAGO CARDIEL'],
            ['province_id'=>78, 'name'=>'BAJO CARACOLES'],
            ['province_id'=>78, 'name'=>'GOBERNADOR GREGORES'],
            ['province_id'=>78, 'name'=>'HIPOLITO YRIGOYEN'],
            ['province_id'=>82, 'name'=>'CAMPO ALBERTENGO'],
            ['province_id'=>82, 'name'=>'CAMPO CHARO'],
            ['province_id'=>82, 'name'=>'CAMPO CHIODI'],
            ['province_id'=>82, 'name'=>'CAMPO EL RAFANGO'],
            ['province_id'=>82, 'name'=>'CAMPO GIMBATTI'],
            ['province_id'=>82, 'name'=>'CAMPO LA ORIENTAL'],
            ['province_id'=>82, 'name'=>'CAMPO LA PRADERA'],
            ['province_id'=>82, 'name'=>'CAMPO LOS TRONCOS'],
            ['province_id'=>82, 'name'=>'CAMPO MARINZALDA'],
            ['province_id'=>82, 'name'=>'CAMPO SANTA ISABEL'],
            ['province_id'=>82, 'name'=>'CAMPO SPAGNOLO'],
            ['province_id'=>82, 'name'=>'LOS NOGALES'],
            ['province_id'=>82, 'name'=>'LOS QUIRQUINCHOS'],
            ['province_id'=>82, 'name'=>'SAN JOSE DE LA ESQUINA'],
            ['province_id'=>82, 'name'=>'SANFORD'],
            ['province_id'=>82, 'name'=>'VILLADA'],
            ['province_id'=>82, 'name'=>'ROSARIO'],
            ['province_id'=>82, 'name'=>'CAMPO ALMENDRA'],
            ['province_id'=>82, 'name'=>'CAMPO AMBROGGIO'],
            ['province_id'=>82, 'name'=>'CAMPO BAUDINO'],
            ['province_id'=>82, 'name'=>'CAMPO BERTONI'],
            ['province_id'=>82, 'name'=>'CAMPO BORGARELLO'],
            ['province_id'=>82, 'name'=>'CAMPO CANAVESIO'],
            ['province_id'=>82, 'name'=>'CAMPO GIACOSSA'],
            ['province_id'=>82, 'name'=>'CAMPO LA NIEVA'],
            ['province_id'=>82, 'name'=>'CAMPO MORELLO'],
            ['province_id'=>82, 'name'=>'CAMPO PIACENZA'],
            ['province_id'=>82, 'name'=>'CAMPO RISTORTO'],
            ['province_id'=>82, 'name'=>'LA JOSEFINA'],
            ['province_id'=>82, 'name'=>'LA NICOLOSA'],
            ['province_id'=>82, 'name'=>'LA ZULEMA'],
            ['province_id'=>82, 'name'=>'LOS CHARABONES'],
            ['province_id'=>82, 'name'=>'LOS LEONES'],
            ['province_id'=>82, 'name'=>'LOS TABANOS'],
            ['province_id'=>82, 'name'=>'LOS TRES POZOS'],
            ['province_id'=>82, 'name'=>'TOBA'],
            ['province_id'=>82, 'name'=>'VERA'],
            ['province_id'=>86, 'name'=>'CAMPO CONTARDI'],
            ['province_id'=>86, 'name'=>'COLONIA HERMELINDA'],
            ['province_id'=>86, 'name'=>'COLONIA LIBERTAD'],
            ['province_id'=>86, 'name'=>'EL AIBAL'],
            ['province_id'=>86, 'name'=>'EL OSO'],
            ['province_id'=>86, 'name'=>'CRUZ CHICA'],
            ['province_id'=>86, 'name'=>'CUATRO ESQUINAS'],
            ['province_id'=>90, 'name'=>'CEVIL POZO'],
            ['province_id'=>90, 'name'=>'ALDERETES'],
            ['province_id'=>90, 'name'=>'EL CORTE'],
            ['province_id'=>90, 'name'=>'LOS GUTIERREZ'],
            ['province_id'=>90, 'name'=>'BANDA DEL RIO SALI'],
            ['province_id'=>90, 'name'=>'LASTENIA'],
            ['province_id'=>90, 'name'=>'COLOMBRES'],
            ['province_id'=>90, 'name'=>'COLONIA MAYO - BARRIO LA MILAGROSA'],
            ['province_id'=>90, 'name'=>'EL PARAISO'],
            ['province_id'=>90, 'name'=>'EX INGENIO ESPERANZA'],
            ['province_id'=>90, 'name'=>'EX INGENIO LUJAN'],
            ['province_id'=>90, 'name'=>'INGENIO LA FLORIDA'],
            ['province_id'=>90, 'name'=>'LAS CEJAS'],
            ['province_id'=>90, 'name'=>'EX INGENIO LOS RALOS'],
            ['province_id'=>90, 'name'=>'VILLA RECASTE'],
            ['province_id'=>90, 'name'=>'VILLA TERCERA'],
            ['province_id'=>90, 'name'=>'PACARA'],
            ['province_id'=>90, 'name'=>'RANCHILLOS'],
            ['province_id'=>90, 'name'=>'SAN ANDRES'],
            ['province_id'=>90, 'name'=>'BELICHA'],
            ['province_id'=>90, 'name'=>'COCHUNA'],
            ['province_id'=>90, 'name'=>'CORTADERAS'],
            ['province_id'=>90, 'name'=>'EL MILAGRO'],
            ['province_id'=>90, 'name'=>'EL MOLINO'],
            ['province_id'=>90, 'name'=>'FINCA LA FALDA'],
            ['province_id'=>90, 'name'=>'FINCA LEON CORNET'],
            ['province_id'=>90, 'name'=>'GASTONA'],
            ['province_id'=>90, 'name'=>'GASTONA NORTE'],
            ['province_id'=>90, 'name'=>'GASTONA SUR'],
            ['province_id'=>90, 'name'=>'GASTONILLA'],
            ['province_id'=>90, 'name'=>'ILTICO'],
            ['province_id'=>90, 'name'=>'LA CALERA'],
            ['province_id'=>90, 'name'=>'LA ESPERANZA'],
            ['province_id'=>90, 'name'=>'LA HIGUERA'],
            ['province_id'=>90, 'name'=>'LAS FALDAS'],
            ['province_id'=>90, 'name'=>'LAS LENGUAS'],
            ['province_id'=>90, 'name'=>'LAS PAVAS'],
            ['province_id'=>90, 'name'=>'MONTE RICO VIEJO'],
            ['province_id'=>90, 'name'=>'MUYO'],
            ['province_id'=>90, 'name'=>'SAN CARLOS'],
            ['province_id'=>90, 'name'=>'SAN RAMON'],
            ['province_id'=>90, 'name'=>'YUCUMANITA'],
            ['province_id'=>90, 'name'=>'ALPACHIRI'],
            ['province_id'=>90, 'name'=>'ALTO VERDE'],
            ['province_id'=>90, 'name'=>'ARCADIA'],
            ['province_id'=>90, 'name'=>'SAN ROQUE'],
            ['province_id'=>90, 'name'=>'CONCEPCION'],
            ['province_id'=>90, 'name'=>'ILTICO'],
            ['province_id'=>90, 'name'=>'LA TRINIDAD'],
            ['province_id'=>90, 'name'=>'MEDINA'],
            ['province_id'=>90, 'name'=>'AGUA BLANCA'],
            ['province_id'=>90, 'name'=>'BARRIO OESTE'],
            ['province_id'=>90, 'name'=>'COLONIA SOBRECASAS'],
            ['province_id'=>90, 'name'=>'CUMBRE EL MATADERO'],
            ['province_id'=>90, 'name'=>'EL CRUCE'],
            ['province_id'=>90, 'name'=>'ESTACION PADILLA'],
            ['province_id'=>90, 'name'=>'KILOMETRO102'],
            ['province_id'=>90, 'name'=>'LA RINCONADA'],
            ['province_id'=>90, 'name'=>'MONTE GRANDE'],
            ['province_id'=>90, 'name'=>'SAN GABRIEL'],
            ['province_id'=>90, 'name'=>'SAN GABRIEL DEL MONTE'],
            ['province_id'=>90, 'name'=>'SANTA CLARA'],
            ['province_id'=>90, 'name'=>'BARRIO CASA ROSADA'],
            ['province_id'=>90, 'name'=>'CAMPO DE HERRERA'],
            ['province_id'=>90, 'name'=>'EX INGENIO NUEVA BAVIERA'],
            ['province_id'=>90, 'name'=>'FAMAILLA'],
            ['province_id'=>90, 'name'=>'INGENIO FRONTERITA'],
            ['province_id'=>90, 'name'=>'ALTO DEL PUESTO'],
            ['province_id'=>90, 'name'=>'AMUMPA'],
            ['province_id'=>90, 'name'=>'ARBOLES GRANDES'],
            ['province_id'=>90, 'name'=>'BARRANCAS'],
            ['province_id'=>90, 'name'=>'BARRANQUERAS'],
            ['province_id'=>90, 'name'=>'CAMPO BELLO'],
            ['province_id'=>90, 'name'=>'CAMPO GRANDE'],
            ['province_id'=>90, 'name'=>'CASAS VIEJAS'],
            ['province_id'=>90, 'name'=>'CHACRAS VIEJAS'],
            ['province_id'=>90, 'name'=>'DOS POZOS'],
            ['province_id'=>90, 'name'=>'EL DURAZNO'],
            ['province_id'=>90, 'name'=>'EL JARDIN'],
            ['province_id'=>90, 'name'=>'EL MISTOL'],
            ['province_id'=>90, 'name'=>'EL PARAISO'],
            ['province_id'=>90, 'name'=>'EL PUESTITO'],
            ['province_id'=>90, 'name'=>'EL QUEBRACHITO'],
            ['province_id'=>90, 'name'=>'EL SIMBOL'],
            ['province_id'=>90, 'name'=>'EL ZAPALLAR'],
            ['province_id'=>90, 'name'=>'ICHIPUCA'],
            ['province_id'=>90, 'name'=>'LA CHILCA'],
            ['province_id'=>90, 'name'=>'LA ESPERANZA'],
            ['province_id'=>90, 'name'=>'LA FLORIDA'],
            ['province_id'=>90, 'name'=>'LA IGUANA'],
            ['province_id'=>90, 'name'=>'LA LOMA'],
            ['province_id'=>90, 'name'=>'LAGUNA LARGA'],
            ['province_id'=>90, 'name'=>'LAS ANIMAS'],
            ['province_id'=>90, 'name'=>'LAS LOMITAS'],
            ['province_id'=>90, 'name'=>'LOS CERCOS'],
            ['province_id'=>90, 'name'=>'LOS DIAZ'],
            ['province_id'=>90, 'name'=>'LOS MISTOLES'],
            ['province_id'=>90, 'name'=>'LOS MOLLES'],
            ['province_id'=>90, 'name'=>'LOS RANCHILLOS'],
            ['province_id'=>90, 'name'=>'LOS RUIZ'],
            ['province_id'=>90, 'name'=>'LOS SAUCES'],
            ['province_id'=>90, 'name'=>'PAEZ'],
            ['province_id'=>90, 'name'=>'POZO HONDO'],
            ['province_id'=>90, 'name'=>'POZO VERDE'],
            ['province_id'=>90, 'name'=>'PUESTO DEL MEDIO'],
            ['province_id'=>90, 'name'=>'PUESTO LOS PEREZ'],
            ['province_id'=>90, 'name'=>'RAMOS'],
            ['province_id'=>90, 'name'=>'SANTA ROSA'],
            ['province_id'=>90, 'name'=>'SOL DE MAYO'],
            ['province_id'=>90, 'name'=>'TACO RODEO'],
            ['province_id'=>90, 'name'=>'TORO MUERTO'],
            ['province_id'=>90, 'name'=>'VILLA PUJIO'],
            ['province_id'=>90, 'name'=>'GRANEROS'],
            ['province_id'=>90, 'name'=>'LAMADRID'],
            ['province_id'=>90, 'name'=>'TACO RALO'],
            ['province_id'=>90, 'name'=>'CAMPO BELLO'],
            ['province_id'=>90, 'name'=>'DONATO ALVAREZ'],
            ['province_id'=>90, 'name'=>'EL CHURQUI'],
            ['province_id'=>90, 'name'=>'EL MOLLAR'],
            ['province_id'=>90, 'name'=>'ESCABA DE ABAJO'],
            ['province_id'=>90, 'name'=>'ESCABA DE ARRIBA'],
            ['province_id'=>90, 'name'=>'LA CALERA'],
            ['province_id'=>90, 'name'=>'NARANJO ESQUINA'],
            ['province_id'=>90, 'name'=>'TALAMUYO'],
            ['province_id'=>90, 'name'=>'YAQUILO'],
            ['province_id'=>90, 'name'=>'JUAN BAUTISTA ALBERDI'],
            ['province_id'=>90, 'name'=>'VILLA BELGRANO'],
            ['province_id'=>90, 'name'=>'ALTO DE LA COCHA'],
            ['province_id'=>90, 'name'=>'ALTO DEL PUESTO'],
            ['province_id'=>90, 'name'=>'BAJASTINE'],
            ['province_id'=>90, 'name'=>'CASAS VIEJAS'],
            ['province_id'=>90, 'name'=>'EL CORRALITO'],
            ['province_id'=>90, 'name'=>'EL NOGAL'],
            ['province_id'=>90, 'name'=>'EL PORVENIR'],
            ['province_id'=>90, 'name'=>'EL POTRERILLO'],
            ['province_id'=>90, 'name'=>'EL SACRIFICIO'],
            ['province_id'=>90, 'name'=>'HUACRA'],
            ['province_id'=>90, 'name'=>'HUASA PAMPA SUR'],
            ['province_id'=>90, 'name'=>'LA INVERNADA'],
            ['province_id'=>90, 'name'=>'LA POSTA'],
            ['province_id'=>90, 'name'=>'LA SALVACION'],
            ['province_id'=>90, 'name'=>'MONTE GRANDE'],
            ['province_id'=>90, 'name'=>'POZO DE LA ESQUINA'],
            ['province_id'=>90, 'name'=>'PUEBLO VIEJO'],
            ['province_id'=>90, 'name'=>'QUEBRACHITO'],
            ['province_id'=>90, 'name'=>'RUMI PUNCO'],
            ['province_id'=>90, 'name'=>'VILLA NUEVA'],
            ['province_id'=>90, 'name'=>'YANIMAS'],
            ['province_id'=>90, 'name'=>'LA COCHA'],
            ['province_id'=>90, 'name'=>'SAN JOSE DE LA COCHA'],
            ['province_id'=>90, 'name'=>'AGUA AZUL'],
            ['province_id'=>90, 'name'=>'AGUA DULCE'],
            ['province_id'=>90, 'name'=>'AGUA SALADA'],
            ['province_id'=>90, 'name'=>'AMAICHA DEL LLANO'],
            ['province_id'=>90, 'name'=>'CAMPO AZUL'],
            ['province_id'=>90, 'name'=>'CARANCHO POZO'],
            ['province_id'=>90, 'name'=>'CONDOR HUASI'],
            ['province_id'=>90, 'name'=>'EL CARMEN'],
            ['province_id'=>90, 'name'=>'EL CORTADERAL'],
            ['province_id'=>90, 'name'=>'EL GUARDAMONTE'],
            ['province_id'=>90, 'name'=>'EL MOJON'],
            ['province_id'=>90, 'name'=>'EL MOLLAR'],
            ['province_id'=>90, 'name'=>'EL QUIMIL'],
            ['province_id'=>90, 'name'=>'EL SUNCHAL'],
            ['province_id'=>90, 'name'=>'ENTRE RIOS'],
            ['province_id'=>90, 'name'=>'ERIN'],
            ['province_id'=>90, 'name'=>'ESQUINA'],
            ['province_id'=>90, 'name'=>'ESQUINA DEL LLANO'],
            ['province_id'=>90, 'name'=>'ESTACION CACHI YACO'],
            ['province_id'=>90, 'name'=>'ESTACION LA ENCANTADA'],
            ['province_id'=>90, 'name'=>'FINCA TINA'],
            ['province_id'=>90, 'name'=>'LA BOLSA'],
            ['province_id'=>90, 'name'=>'LA ENCRUCIJADA'],
            ['province_id'=>90, 'name'=>'LA FLORIDA'],
            ['province_id'=>90, 'name'=>'LAGUNA BLANCA'],
            ['province_id'=>90, 'name'=>'LAS MERCEDES'],
            ['province_id'=>90, 'name'=>'LAS TALAS'],
            ['province_id'=>90, 'name'=>'LAS TUSQUITAS'],
            ['province_id'=>90, 'name'=>'LOMA VERDE'],
            ['province_id'=>90, 'name'=>'LOS BRITOS'],
            ['province_id'=>90, 'name'=>'LOS CAMPEROS'],
            ['province_id'=>90, 'name'=>'LOS DIAZ'],
            ['province_id'=>90, 'name'=>'LOS HERRERA'],
            ['province_id'=>90, 'name'=>'LOS JUAREZ'],
            ['province_id'=>90, 'name'=>'LOS QUEMADOS'],
            ['province_id'=>90, 'name'=>'LOS SUELDOS'],
            ['province_id'=>90, 'name'=>'MANCHALA'],
            ['province_id'=>90, 'name'=>'MANCOPA'],
            ['province_id'=>90, 'name'=>'MANCOPA CHICO'],
            ['province_id'=>90, 'name'=>'MIXTA'],
            ['province_id'=>90, 'name'=>'MOLLE POZO'],
            ['province_id'=>90, 'name'=>'MONTE BELLO'],
            ['province_id'=>90, 'name'=>'ORAN'],
            ['province_id'=>90, 'name'=>'PUESTO CHICO'],
            ['province_id'=>90, 'name'=>'PUMA POZO'],
            ['province_id'=>90, 'name'=>'QUILMES'],
            ['province_id'=>90, 'name'=>'ROMERA POZO'],
            ['province_id'=>90, 'name'=>'SAN ANTONIO'],
            ['province_id'=>90, 'name'=>'SAN JOSE DE BUENA VISTA'],
            ['province_id'=>90, 'name'=>'SAN NICOLAS'],
            ['province_id'=>90, 'name'=>'SAN RAMON'],
            ['province_id'=>90, 'name'=>'TRES POZOS'],
            ['province_id'=>90, 'name'=>'TUSCA POZO'],
            ['province_id'=>90, 'name'=>'VICLOS'],
            ['province_id'=>90, 'name'=>'VIZCACHERAL'],
            ['province_id'=>90, 'name'=>'YALAPA'],
            ['province_id'=>90, 'name'=>'BELLA VISTA'],
            ['province_id'=>90, 'name'=>'ESTACION ARAOZ'],
            ['province_id'=>90, 'name'=>'LOS PUESTOS'],
            ['province_id'=>90, 'name'=>'MANUEL GARCIA FERNANDEZ'],
            ['province_id'=>90, 'name'=>'PALA PALA'],
            ['province_id'=>90, 'name'=>'RIO COLORADO'],
            ['province_id'=>90, 'name'=>'SANTA ROSA DE LEALES'],
            ['province_id'=>90, 'name'=>'VILLA FIAD - INGENIO LEALES'],
            ['province_id'=>90, 'name'=>'VILLA DE LEALES'],
            ['province_id'=>90, 'name'=>'EL CEIBAL'],
            ['province_id'=>90, 'name'=>'EL DURAZNILLO'],
            ['province_id'=>90, 'name'=>'EL NOGALITO'],
            ['province_id'=>90, 'name'=>'LA BOLSA'],
            ['province_id'=>90, 'name'=>'LA RINCONADA'],
            ['province_id'=>90, 'name'=>'LOS AGUIRRE'],
            ['province_id'=>90, 'name'=>'LOS NOGALITOS'],
            ['province_id'=>90, 'name'=>'MALA MALA'],
            ['province_id'=>90, 'name'=>'MUNDO NUEVO'],
            ['province_id'=>90, 'name'=>'POTRERO DE LAS TABLAS'],
            ['province_id'=>90, 'name'=>'POTRERO GRANDE'],
            ['province_id'=>90, 'name'=>'PUENTE EL MANANTIAL'],
            ['province_id'=>90, 'name'=>'PUNTA DEL MONTE'],
            ['province_id'=>90, 'name'=>'SAN RAFAEL'],
            ['province_id'=>90, 'name'=>'SANTA BARBARA'],
            ['province_id'=>90, 'name'=>'TECOTEX'],
            ['province_id'=>90, 'name'=>'BARRIO SAN FELIPE'],
            ['province_id'=>90, 'name'=>'BARRIO ARAUJO'],
            ['province_id'=>90, 'name'=>'EL MANANTIAL'],
            ['province_id'=>90, 'name'=>'INGENIO SAN PABLO'],
            ['province_id'=>90, 'name'=>'LA REDUCCION'],
            ['province_id'=>90, 'name'=>'LULES'],
            ['province_id'=>90, 'name'=>'ALTO DE LEIVA'],
            ['province_id'=>90, 'name'=>'AMBERES'],
            ['province_id'=>90, 'name'=>'CASPINCHANGO'],
            ['province_id'=>90, 'name'=>'EL CERCADO'],
            ['province_id'=>90, 'name'=>'EL CHURQUI'],
            ['province_id'=>90, 'name'=>'EL NARANJAL'],
            ['province_id'=>90, 'name'=>'HUASA PAMPA'],
            ['province_id'=>90, 'name'=>'ISLA SAN JOSE'],
            ['province_id'=>90, 'name'=>'LA CIENAGA'],
            ['province_id'=>90, 'name'=>'LA FLORIDA'],
            ['province_id'=>90, 'name'=>'LA RAMADITA'],
            ['province_id'=>90, 'name'=>'LAS MESADAS'],
            ['province_id'=>90, 'name'=>'LOS ROBLES'],
            ['province_id'=>90, 'name'=>'LOS ROJOS'],
            ['province_id'=>90, 'name'=>'LOS SOSA'],
            ['province_id'=>90, 'name'=>'ORAN'],
            ['province_id'=>90, 'name'=>'PILCO'],
            ['province_id'=>90, 'name'=>'PUEBLO VIEJO'],
            ['province_id'=>90, 'name'=>'RINCON DE BALDERRAMA'],
            ['province_id'=>90, 'name'=>'SAN JOSE DE FLORES'],
            ['province_id'=>90, 'name'=>'YACUCHINA'],
            ['province_id'=>90, 'name'=>'YONOPONGO'],
            ['province_id'=>90, 'name'=>'ACHERAL'],
            ['province_id'=>90, 'name'=>'CAPITAN CACERES'],
            ['province_id'=>90, 'name'=>'MONTEROS'],
            ['province_id'=>90, 'name'=>'PUEBLO INDEPENDENCIA'],
            ['province_id'=>90, 'name'=>'RIO SECO'],
            ['province_id'=>90, 'name'=>'SANTA LUCIA'],
            ['province_id'=>90, 'name'=>'SARGENTO MOYA'],
            ['province_id'=>90, 'name'=>'SOLDADO MALDONADO'],
            ['province_id'=>90, 'name'=>'TENIENTE BERDINA'],
            ['province_id'=>90, 'name'=>'VILLA QUINTEROS'],
            ['province_id'=>90, 'name'=>'COLONIA SANTA BARBARA'],
            ['province_id'=>90, 'name'=>'EL RODEO'],
            ['province_id'=>90, 'name'=>'EL TUSCAL'],
            ['province_id'=>90, 'name'=>'LA TIPA'],
            ['province_id'=>90, 'name'=>'LAS ANIMAS'],
            ['province_id'=>90, 'name'=>'LOS CORDOBA'],
            ['province_id'=>90, 'name'=>'LOS RIOS'],
            ['province_id'=>90, 'name'=>'MONTE BELLO'],
            ['province_id'=>90, 'name'=>'MONTE REDONDO'],
            ['province_id'=>90, 'name'=>'SAN MIGUEL'],
            ['province_id'=>90, 'name'=>'SANTA ROSA'],
            ['province_id'=>90, 'name'=>'AGUILARES'],
            ['province_id'=>90, 'name'=>'INGENIO SANTA BARBARA'],
            ['province_id'=>90, 'name'=>'LOS SARMIENTOS'],
            ['province_id'=>90, 'name'=>'RIO CHICO'],
            ['province_id'=>90, 'name'=>'SANTA ANA'],
            ['province_id'=>90, 'name'=>'VILLA CLODOMIRO HILERET'],
            ['province_id'=>90, 'name'=>'SAN MIGUEL DE TUCUMAN'],
            ['province_id'=>90, 'name'=>'ALTO DE LAS LECHUZAS'],
            ['province_id'=>90, 'name'=>'AMPATA'],
            ['province_id'=>90, 'name'=>'ARROYO ATAHONA'],
            ['province_id'=>90, 'name'=>'BALDERRAMA'],
            ['province_id'=>90, 'name'=>'BALDERRAMA SUR'],
            ['province_id'=>90, 'name'=>'BUENA VISTA'],
            ['province_id'=>90, 'name'=>'BUENA VISTA OESTE'],
            ['province_id'=>90, 'name'=>'CAMPO VOLANTE'],
            ['province_id'=>90, 'name'=>'CEJAS DE AROCA'],
            ['province_id'=>90, 'name'=>'CIUDACITA'],
            ['province_id'=>90, 'name'=>'EL DURAZNO'],
            ['province_id'=>90, 'name'=>'EL JARDIN'],
            ['province_id'=>90, 'name'=>'EL MOLLAR'],
            ['province_id'=>90, 'name'=>'EL OVAL'],
            ['province_id'=>90, 'name'=>'EL PACARA'],
            ['province_id'=>90, 'name'=>'EL PUESTO'],
            ['province_id'=>90, 'name'=>'ESTACION MANUELA PEDRAZA'],
            ['province_id'=>90, 'name'=>'GUEMES'],
            ['province_id'=>90, 'name'=>'LA JUNTA'],
            ['province_id'=>90, 'name'=>'LA REINA'],
            ['province_id'=>90, 'name'=>'LA RINCONADA'],
            ['province_id'=>90, 'name'=>'LA TUNA'],
            ['province_id'=>90, 'name'=>'LAS CEJAS'],
            ['province_id'=>90, 'name'=>'LAS JUNTAS'],
            ['province_id'=>90, 'name'=>'LAS TALITAS'],
            ['province_id'=>90, 'name'=>'LAZARTE'],
            ['province_id'=>90, 'name'=>'LOMA DE CIUDACITA'],
            ['province_id'=>90, 'name'=>'LOS AMAYA'],
            ['province_id'=>90, 'name'=>'LOS PEREZ'],
            ['province_id'=>90, 'name'=>'NIOGASTA'],
            ['province_id'=>90, 'name'=>'PALOMINOS'],
            ['province_id'=>90, 'name'=>'PAMPA MAYO'],
            ['province_id'=>90, 'name'=>'PUESTO LOS VALDEZ'],
            ['province_id'=>90, 'name'=>'SAN ANTONIO DE PADUA'],
            ['province_id'=>90, 'name'=>'SAN PEDRO MARTIR'],
            ['province_id'=>90, 'name'=>'SANTA ISABEL'],
            ['province_id'=>90, 'name'=>'SUR DE LAZARTE'],
            ['province_id'=>90, 'name'=>'SUR DE TREJOS'],
            ['province_id'=>90, 'name'=>'YACUCHIRI'],
            ['province_id'=>90, 'name'=>'YERBA BUENA'],
            ['province_id'=>90, 'name'=>'ATAHONA'],
            ['province_id'=>90, 'name'=>'MONTEAGUDO'],
            ['province_id'=>90, 'name'=>'NUEVA TRINIDAD'],
            ['province_id'=>90, 'name'=>'SANTA CRUZ'],
            ['province_id'=>90, 'name'=>'SIMOCA'],
            ['province_id'=>90, 'name'=>'VILLA CHICLIGASTA'],
            ['province_id'=>90, 'name'=>'AMPIMPA'],
            ['province_id'=>90, 'name'=>'ANJUANA'],
            ['province_id'=>90, 'name'=>'CALIMONTE'],
            ['province_id'=>90, 'name'=>'EL ARBOLAR'],
            ['province_id'=>90, 'name'=>'EL CARMEN'],
            ['province_id'=>90, 'name'=>'EL INFIERNILLO'],
            ['province_id'=>90, 'name'=>'EL PASO'],
            ['province_id'=>90, 'name'=>'EL RINCON'],
            ['province_id'=>90, 'name'=>'EL TIO'],
            ['province_id'=>90, 'name'=>'ESQUINA DEL VALLE'],
            ['province_id'=>90, 'name'=>'LA ANGOSTURA'],
            ['province_id'=>90, 'name'=>'LA BOLSA'],
            ['province_id'=>90, 'name'=>'LA CIENAGA'],
            ['province_id'=>90, 'name'=>'LA FRONTERITA'],
            ['province_id'=>90, 'name'=>'LA HOYADA'],
            ['province_id'=>90, 'name'=>'LA JUNTA'],
            ['province_id'=>90, 'name'=>'LARA'],
            ['province_id'=>90, 'name'=>'LAS CARRERAS'],
            ['province_id'=>90, 'name'=>'LAS TACANAS'],
            ['province_id'=>90, 'name'=>'LOS CUARTOS'],
            ['province_id'=>90, 'name'=>'LOS ZAZOS'],
            ['province_id'=>90, 'name'=>'OJO DE AGUA'],
            ['province_id'=>90, 'name'=>'PICHAO'],
            ['province_id'=>90, 'name'=>'QUILMES'],
            ['province_id'=>90, 'name'=>'RINCON DE QUILMES'],
            ['province_id'=>90, 'name'=>'RODEO GRANDE'],
            ['province_id'=>90, 'name'=>'SALAS'],
            ['province_id'=>90, 'name'=>'SANTA CRUZ'],
            ['province_id'=>90, 'name'=>'TIO PUNCO'],
            ['province_id'=>90, 'name'=>'YASYAMAYO'],
            ['province_id'=>90, 'name'=>'AMAICHA DEL VALLE'],
            ['province_id'=>90, 'name'=>'COLALAO DEL VALLE'],
            ['province_id'=>90, 'name'=>'EL MOLLAR'],
            ['province_id'=>90, 'name'=>'TAFI DEL VALLE'],
            ['province_id'=>90, 'name'=>'ALTO DE ANFAMA'],
            ['province_id'=>90, 'name'=>'ANCAJULI'],
            ['province_id'=>90, 'name'=>'NUEVA ESPERANZA'],
            ['province_id'=>90, 'name'=>'RACO'],
            ['province_id'=>90, 'name'=>'SAN JOSE DE CHASQUIVIL'],
            ['province_id'=>90, 'name'=>'SAN JOSE DE RACO'],
            ['province_id'=>90, 'name'=>'BARRIO EL CRUCE'],
            ['province_id'=>90, 'name'=>'BARRIO LOMAS DE TAFI'],
            ['province_id'=>90, 'name'=>'BARRIO MUTUAL SAN MARTIN'],
            ['province_id'=>90, 'name'=>'DIAG. NORTE - LUZ Y FUERZA - LOS POCITOS'],
            ['province_id'=>90, 'name'=>'EL CADILLAL'],
            ['province_id'=>90, 'name'=>'TAFI VIEJO'],
            ['province_id'=>90, 'name'=>'VILLA LAS FLORES'],
            ['province_id'=>90, 'name'=>'VILLA MARIANO MORENO - EL COLMENAR'],
            ['province_id'=>90, 'name'=>'SAN PEDRO DE COLALAO'],
            ['province_id'=>90, 'name'=>'VILLA DE TRANCAS'],
            ['province_id'=>90, 'name'=>'CEVIL REDONDO'],
            ['province_id'=>90, 'name'=>'COLONIA SAN JOSE'],
            ['province_id'=>90, 'name'=>'CURVA DE LOS VEGAS'],
            ['province_id'=>90, 'name'=>'EL CORTE'],
            ['province_id'=>90, 'name'=>'SAN JAVIER'],
            ['province_id'=>90, 'name'=>'VILLA SAN JAVIER'],
            ['province_id'=>90, 'name'=>'BARRIO SAN JOSE III'],
            ['province_id'=>90, 'name'=>'BARRIO SAN JOSE III'],
            ['province_id'=>90, 'name'=>'COUNTRY JOCKEY CLUB'],
            ['province_id'=>90, 'name'=>'VILLA CARMELA'],
            ['province_id'=>90, 'name'=>'EX INGENIO SAN JOSE'],
            ['province_id'=>90, 'name'=>'YERBA BUENA - MARCOS PAZ'],
            ['province_id'=>94, 'name'=>'CULLEN'],
            ['province_id'=>94, 'name'=>'EL PARAMO'],
            ['province_id'=>94, 'name'=>'ESTANCIA SARA'],
            ['province_id'=>94, 'name'=>'SAN SEBASTIAN'],
            ['province_id'=>94, 'name'=>'RIO GRANDE'],
            ['province_id'=>94, 'name'=>'TOLHUIN'],
            ['province_id'=>94, 'name'=>'LAGUNA ESCONDIDA'],
            ['province_id'=>94, 'name'=>'USHUAIA'],
            ['province_id'=>94, 'name'=>'PUERTO DARWIN'],
            ['province_id'=>94, 'name'=>'PUERTO LEITH'],
            ['province_id'=>94, 'name'=>'PUERTO ARGENTINO'],
            ['province_id'=>94, 'name'=>'BASE MARAMBIO'],
            ['province_id'=>94, 'name'=>'BASE ESPERANZA'],
            ['province_id'=>94, 'name'=>'BASE BELGRANO II'],
            ['province_id'=>94, 'name'=>'BASE BROWN'],
            ['province_id'=>94, 'name'=>'BASE MATIENZO'],
        ];

        foreach($cities as $city) {
            City::create($city);
        }
    }
}
